/* =========================================================
   DINGEL HAFIZIA MADRASA — FINAL APP.JS
========================================================= */
const firebaseConfig={apiKey:"AIzaSyCmoFXa6eYEi-SV_Otk9c-l4TlHWXzMFQU",authDomain:"dingel-hafizia-manager.firebaseapp.com",projectId:"dingel-hafizia-manager",storageBucket:"dingel-hafizia-manager.firebasestorage.app",messagingSenderId:"1019481403108",appId:"1:1019481403108:web:06b44cac27a54a557d86f1",measurementId:"G-FPETR4EDYP"};
if(!firebase.apps.length)firebase.initializeApp(firebaseConfig);
const db=firebase.firestore(),PASSWORD="123",MONTHS=["জানুয়ারি","ফেব্রুয়ারি","মার্চ","এপ্রিল","মে","জুন","জুলাই","আগস্ট","সেপ্টেম্বর","অক্টোবর","নভেম্বর","ডিসেম্বর"];
let students=[],collections=[],studentPage=1;const PAGE=15;
const $=id=>document.getElementById(id), val=id=>$(id)?$(id).value.trim():"";
function set(id,v){if($(id))$(id).innerText=v}
function put(id,v){if($(id))$(id).value=v??""}
function bn(n){const m={"0":"০","1":"১","2":"২","3":"৩","4":"৪","5":"৫","6":"৬","7":"৭","8":"৮","9":"৯"};return String(n??"").replace(/[0-9]/g,x=>m[x])}
function money(n){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(n)||0)}
function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function typeOf(v){let x=String(v||"").toLowerCase();return x.includes("orphan")||x.includes("atim")||x.includes("এতিম")?"Orphan":x.includes("poor")||x.includes("n rsd")||x.includes("দরিদ্র")||x.includes("গরিব")?"Poor":"General"}
function monthNow(){return MONTHS[new Date().getMonth()]}
function todayISO(){let d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function toast(msg,err=false){let t=$("toast");if(!t){alert(msg);return}set("toastMessage",msg);$("toastIcon").className=err?"fa-solid fa-circle-exclamation":"fa-solid fa-circle-check";t.classList.add("show");clearTimeout(window.__t);window.__t=setTimeout(()=>t.classList.remove("show"),3200)}
function loading(on,text="ডাটা লোড হচ্ছে..."){$("loadingScreen")?.classList.toggle("hidden",!on);if($("loadingText"))$("loadingText").innerText=text}
function handleLogin(e){e?.preventDefault();if(val("passwordInput")===PASSWORD){localStorage.setItem("dingelLoggedIn","true");$("loginScreen").classList.add("hidden");$("app").classList.remove("hidden");$("errorMessage").style.display="none";put("passwordInput","");loadApplicationData()}else{$("errorMessage").style.display="block";put("passwordInput","");$("passwordInput").focus()}}
function togglePassword(){let i=$("passwordInput"),ic=$("passwordIcon");if(!i)return;i.type=i.type==="password"?"text":"password";ic.className=i.type==="password"?"fa-solid fa-eye":"fa-solid fa-eye-slash"}
function handleLogout(){localStorage.removeItem("dingelLoggedIn");$("app").classList.add("hidden");$("loginScreen").classList.remove("hidden")}
function openSidebar(){$("sidebar")?.classList.add("open");$("sidebarOverlay")?.classList.add("show")}
function closeSidebar(){$("sidebar")?.classList.remove("open");$("sidebarOverlay")?.classList.remove("show")}
function showSection(id){document.querySelectorAll(".content-section").forEach(x=>x.classList.add("hidden"));$(id)?.classList.remove("hidden");document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.section===id));let t={dashboardSection:["ড্যাশবোর্ড","মাদ্রাসার সামগ্রিক হিসাব ও তথ্য"],studentsSection:["ছাত্র তালিকা","ছাত্র তথ্য ও ব্যবস্থাপনা"],collectionSection:["ফি আদায়","সকল ফি জমার রেকর্ড"],reportsSection:["রিপোর্ট","আর্থিক ও ছাত্র সংক্রান্ত রিপোর্ট"]}[id];if(t){set("pageTitle",t[0]);set("pageSubtitle",t[1])}closeSidebar()}
async function loadApplicationData(){loading(true);try{await Promise.all([fetchStudents(),fetchCollections()]);renderAll()}catch(e){console.error(e);toast("Firebase ডাটা লোড করতে সমস্যা হয়েছে। Firestore Rules পরীক্ষা করুন।",true)}finally{loading(false)}}
async function fetchStudents(){let s=await db.collection("students").get();if(!s.empty)students=s.docs.map(d=>({id:d.id,...d.data()}));else{try{let r=await fetch("students.json");let a=r.ok?await r.json():[];students=a.filter(x=>x.name).map(x=>{let m=String(x.monthly||"").trim().toUpperCase();return{id:"json_"+x.roll,roll:x.roll,name:x.name,class:x.class||"",guardian:x.father||"N/A",phone:x.number||"N/A",address:x.address||"",type:m==="ATIM"?"Orphan":m==="N RSD"?"Poor":"General",monthly:["ATIM","N RSD",""].includes(m)?0:Number(m)||0}})}catch{students=[]}}students.sort((a,b)=>String(a.roll||"").localeCompare(String(b.roll||""),undefined,{numeric:true}))}
async function fetchCollections(){let s=await db.collection("collections").get();collections=s.docs.map(d=>({id:d.id,...d.data()}));collections.sort((a,b)=>new Date(b.date||0)-new Date(a.date||0))}
function renderAll(){renderStudents();renderCollections();renderRecent();dashboard();reports()}
function dashboard(){let total=collections.reduce((a,x)=>a+Number(x.amount||0),0),monthly=collections.filter(x=>x.month===monthNow()).reduce((a,x)=>a+Number(x.amount||0),0),free=students.filter(x=>["Orphan","Poor"].includes(typeOf(x.type))).length;set("totalStudents",bn(students.length));set("totalCollection",money(total));set("monthlyCollection",money(monthly));set("freeStudents",bn(free));set("collectionPageTotal",money(total));set("totalReceipts",bn(collections.length))}
function openStudentModal(id=null){$("addStudentForm").reset();put("editingStudentId","");if(id){let s=students.find(x=>x.id===id);if(!s)return;set("studentModalTitle","ছাত্রের তথ্য এডিট");put("editingStudentId",s.id);put("studentName",s.name);put("studentRoll",s.roll);put("studentClass",s.class);put("guardianName",s.guardian);put("guardianPhone",s.phone==="N/A"?"":s.phone);put("studentType",typeOf(s.type));put("studentMonthly",s.monthly||"")}else set("studentModalTitle","নতুন ছাত্র ভর্তি");$("studentModal").classList.remove("hidden")}
function closeStudentModal(){$("studentModal").classList.add("hidden")}
function openCollectionModal(){put("collectionDate",todayISO());put("collectionMonth",monthNow());put("collectionAmount","");$("collectionStudent").innerHTML='<option value="">ছাত্র নির্বাচন করুন</option>'+students.map(s=>`<option value="${esc(s.id)}">${esc(s.roll)} — ${esc(s.name)}</option>`).join("");$("collectionModal").classList.remove("hidden")}
function closeCollectionModal(){$("collectionModal").classList.add("hidden")}
async function saveStudent(e){e?.preventDefault();let name=val("studentName"),roll=val("studentRoll"),cls=val("studentClass"),guardian=val("guardianName"),phone=val("guardianPhone"),type=typeOf(val("studentType")),monthly=Number(val("studentMonthly"))||0,id=val("editingStudentId");if(!name||!roll||!cls)return toast("নাম, রোল ও শ্রেণী অবশ্যই দিতে হবে।",true);if(phone&&!/^[6-9]\d{9}$/.test(phone))return toast("সঠিক ১০ সংখ্যার ভারতীয় মোবাইল নম্বর দিন।",true);if(students.some(s=>String(s.roll)===String(roll)&&s.id!==id))return toast("এই রোল নম্বরের ছাত্র ইতিমধ্যে আছে।",true);let data={name,roll,class:cls,guardian:guardian||"N/A",phone:phone||"N/A",type,monthly:["Orphan","Poor"].includes(type)?0:monthly,updatedAt:firebase.firestore.FieldValue.serverTimestamp()};try{loading(true,id?"তথ্য আপডেট হচ্ছে...":"নতুন ছাত্র সেভ হচ্ছে...");if(id){await db.collection("students").doc(id).update(data);let i=students.findIndex(s=>s.id===id);if(i>=0)students[i]={...students[i],...data};toast("ছাত্রের তথ্য আপডেট হয়েছে।")}else{data.createdAt=firebase.firestore.FieldValue.serverTimestamp();let r=await db.collection("students").add(data);students.push({id:r.id,...data});toast("নতুন ছাত্র যোগ হয়েছে।")}closeStudentModal();renderAll()}catch(e){console.error(e);toast("ছাত্র সেভ করতে সমস্যা হয়েছে।",true)}finally{loading(false)}}
async function deleteStudent(id){let s=students.find(x=>x.id===id);if(!s||!confirm(`"${s.name}"-কে মুছে ফেলবেন?`))return;try{loading(true,"ছাত্র মুছে ফেলা হচ্ছে...");await db.collection("students").doc(id).delete();students=students.filter(x=>x.id!==id);renderAll();toast("ছাত্র মুছে ফেলা হয়েছে।")}catch(e){toast("ছাত্র মুছতে সমস্যা হয়েছে।",true)}finally{loading(false)}}
function renderStudents(){let b=$("studentsTableBody");if(!b)return;let q=val("studentSearch").toLowerCase(),list=students.filter(s=>!q||[s.name,s.roll,s.class,s.guardian,s.phone].join(" ").toLowerCase().includes(q)),pages=Math.max(1,Math.ceil(list.length/PAGE));studentPage=Math.min(studentPage,pages);let start=(studentPage-1)*PAGE,items=list.slice(start,start+PAGE);b.innerHTML=items.length?items.map((s,i)=>{let t=typeOf(s.type),l=t==="Orphan"?"এতিম":t==="Poor"?"দরিদ্র":"সাধারণ";return`<tr><td>${bn(start+i+1)}</td><td>${esc(s.roll)}</td><td><b>${esc(s.name)}</b></td><td>${esc(s.class)}</td><td>${esc(s.guardian)}</td><td>${esc(s.phone)}</td><td>${l}</td><td>${["Orphan","Poor"].includes(t)?"ফ্রি":money(s.monthly)}</td><td><button class="btn-action" onclick="openStudentModal('${esc(s.id)}')"><i class="fa-solid fa-pen"></i></button><button class="btn-action delete" onclick="deleteStudent('${esc(s.id)}')"><i class="fa-solid fa-trash"></i></button></td></tr>`}).join(""):`<tr><td colspan="9" style="text-align:center;padding:30px">কোনো ছাত্র পাওয়া যায়নি।</td></tr>`;set("studentPageInfo",list.length?`${bn(studentPage)} / ${bn(pages)}`:"০");$("studentPrev").disabled=studentPage<=1;$("studentNext").disabled=studentPage>=pages}
function searchStudents(){studentPage=1;renderStudents()}function previousStudentPage(){if(studentPage>1){studentPage--;renderStudents()}}function nextStudentPage(){let q=val("studentSearch").toLowerCase(),n=students.filter(s=>!q||[s.name,s.roll,s.class,s.guardian,s.phone].join(" ").toLowerCase().includes(q)).length,p=Math.max(1,Math.ceil(n/PAGE));if(studentPage<p){studentPage++;renderStudents()}}
async function saveCollection(e){e?.preventDefault();let s=students.find(x=>x.id===val("collectionStudent")),amount=Number(val("collectionAmount"))||0;if(!s)return toast("ছাত্র নির্বাচন করুন।",true);if(amount<=0)return toast("ফি-এর পরিমাণ দিন।",true);if(["Orphan","Poor"].includes(typeOf(s.type)))return toast("এই ছাত্রের ফি ফ্রি।",true);let data={receiptNo:await nextReceipt(),studentId:s.id,studentName:s.name,roll:s.roll,class:s.class,amount,month:val("collectionMonth")||monthNow(),date:val("collectionDate")||todayISO(),note:val("collectionNote"),createdAt:firebase.firestore.FieldValue.serverTimestamp()};try{loading(true,"ফি সেভ হচ্ছে...");let r=await db.collection("collections").add(data);collections.unshift({id:r.id,...data});closeCollectionModal();renderAll();toast("ফি জমা সফল হয়েছে।");setTimeout(()=>printReceipt(data.receiptNo),500)}catch(e){toast("ফি সেভ করতে সমস্যা হয়েছে।",true)}finally{loading(false)}}
async function nextReceipt(){let n=0;collections.forEach(x=>{let m=String(x.receiptNo||"").match(/(\d+)$/);if(m)n=Math.max(n,+m[1])});return`DHM-${new Date().getFullYear()}-${String(n+1).padStart(4,"0")}`}
function renderCollections(){let b=$("collectionsTableBody");if(!b)return;let q=val("collectionSearch").toLowerCase(),list=collections.filter(x=>!q||[x.receiptNo,x.studentName,x.roll,x.class,x.month,x.amount].join(" ").toLowerCase().includes(q));b.innerHTML=list.length?list.map((x,i)=>`<tr><td>${bn(i+1)}</td><td>${esc(x.receiptNo||"-")}</td><td>${esc(x.studentName||"-")}</td><td>${esc(x.roll||"-")}</td><td>${esc(x.class||"-")}</td><td>${esc(x.month||"-")}</td><td><b>${money(x.amount)}</b></td><td>${esc(x.date||"-")}</td><td><button class="btn-action" onclick="printReceipt('${esc(x.receiptNo||x.id)}')"><i class="fa-solid fa-print"></i></button><button class="btn-action delete" onclick="deleteCollection('${esc(x.id)}')"><i class="fa-solid fa-trash"></i></button></td></tr>`).join(""):`<tr><td colspan="9" style="text-align:center;padding:30px">কোনো ফি রেকর্ড নেই।</td></tr>`}
function searchCollections(){renderCollections()}function renderRecent(){let b=$("recentCollectionsBody");if(!b)return;b.innerHTML=collections.slice(0,5).length?collections.slice(0,5).map(x=>`<tr><td>${esc(x.receiptNo)}</td><td>${esc(x.studentName)}</td><td>${esc(x.roll)}</td><td>${esc(x.month)}</td><td><b>${money(x.amount)}</b></td><td>${esc(x.date)}</td></tr>`).join(""):`<tr><td colspan="6" style="text-align:center;padding:25px">কোনো ফি জমা হয়নি।</td></tr>`}
async function deleteCollection(id){let c=collections.find(x=>x.id===id);if(!c||!confirm(`রসিদ ${c.receiptNo||""} মুছে ফেলবেন?`))return;try{loading(true,"রেকর্ড মুছে ফেলা হচ্ছে...");await db.collection("collections").doc(id).delete();collections=collections.filter(x=>x.id!==id);renderAll();toast("রেকর্ড মুছে ফেলা হয়েছে।")}catch(e){toast("রেকর্ড মুছতে সমস্যা হয়েছে।",true)}finally{loading(false)}}
function reports(){let g=students.filter(s=>typeOf(s.type)==="General").length,o=students.filter(s=>typeOf(s.type)==="Orphan").length,p=students.filter(s=>typeOf(s.type)==="Poor").length,total=collections.reduce((a,x)=>a+Number(x.amount||0),0),m=collections.filter(x=>x.month===monthNow()).reduce((a,x)=>a+Number(x.amount||0),0);set("reportTotalStudents",bn(students.length));set("reportGeneralStudents",bn(g));set("reportOrphanStudents",bn(o));set("reportPoorStudents",bn(p));set("reportTotalCollection",money(total));set("reportMonthlyCollection",money(m));$("monthlyReportBody").innerHTML=MONTHS.map(x=>`<tr><td>${x}</td><td>${money(collections.filter(c=>c.month===x).reduce((a,c)=>a+Number(c.amount||0),0))}</td></tr>`).join("")}
function printReceipt(no){let c=collections.find(x=>String(x.receiptNo)===String(no)||String(x.id)===String(no));if(!c)return toast("রসিদ পাওয়া যায়নি।",true);let s=students.find(x=>x.id===c.studentId),w=window.open("","_blank","width=800,height=900");if(!w)return toast("Print window blocked হয়েছে।",true);w.document.write(`<!doctype html><html lang="bn"><head><meta charset="utf-8"><title>${esc(c.receiptNo)}</title><style>@page{size:A5;margin:8mm}body{margin:0;font-family:Arial,"Noto Sans Bengali",sans-serif;background:#eee}.receipt{width:148mm;min-height:190mm;margin:auto;background:#fff;padding:9mm;box-sizing:border-box;border:2px solid #0b6b67;position:relative}.top{text-align:center;border-bottom:2px solid #0b6b67;padding-bottom:12px}.top h1{margin:0;color:#075e5a;font-size:25px}.top p{margin:4px;color:#777}.badge{display:inline-block;margin-top:8px;background:#0b6b67;color:#fff;border-radius:20px;padding:5px 16px}.meta{display:flex;justify-content:space-between;margin:16px 0;font-size:12px}.grid{border:1px solid #ddd}.row{display:grid;grid-template-columns:35% 65%;border-bottom:1px solid #eee}.row:last-child{border:0}.row span{padding:9px;background:#f4f8f7}.row b{padding:9px}.amount{margin-top:18px;border:2px solid #0b6b67;border-radius:10px;padding:14px;text-align:center}.amount small{display:block;color:#777}.amount strong{font-size:27px;color:#075e5a}.sign{display:flex;justify-content:space-between;margin-top:55px;font-size:12px}.sign span{border-top:1px solid #777;padding-top:6px;width:35%;text-align:center}@media print{body{background:#fff}.receipt{margin:0}}</style></head><body><div class="receipt"><div class="top"><h1>ডিঙ্গেল হাফিজিয়া মাদ্রাসা</h1><p>Professional Fee Collection</p><span class="badge">ফি জমার রসিদ</span></div><div class="meta"><span>রসিদ নং: <b>${esc(c.receiptNo)}</b></span><span>তারিখ: <b>${esc(c.date)}</b></span></div><div class="grid"><div class="row"><span>ছাত্রের নাম</span><b>${esc(c.studentName)}</b></div><div class="row"><span>রোল</span><b>${esc(c.roll)}</b></div><div class="row"><span>শ্রেণী</span><b>${esc(c.class)}</b></div><div class="row"><span>অভিভাবক</span><b>${esc(s?.guardian||"-")}</b></div><div class="row"><span>মাস</span><b>${esc(c.month)}</b></div><div class="row"><span>নোট</span><b>${esc(c.note||"-")}</b></div></div><div class="amount"><small>জমার পরিমাণ</small><strong>${money(c.amount)}</strong></div><div class="sign"><span>অভিভাবকের স্বাক্ষর</span><span>মাদ্রাসা কর্তৃপক্ষ</span></div></div><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
function printReport(){window.print()}
function csv(rows,name){let s="\uFEFF"+rows.map(r=>r.map(x=>`"${String(x??"").replace(/"/g,'""')}"`).join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([s],{type:"text/csv;charset=utf-8"}));a.download=name;a.click()}
function exportStudentsCSV(){csv([["Roll","Name","Class","Guardian","Phone","Type","Monthly Fee"],...students.map(s=>[s.roll,s.name,s.class,s.guardian,s.phone,typeOf(s.type),s.monthly])],"dingel-hafizia-students.csv")}
function exportCollectionsCSV(){csv([["Receipt","Student","Roll","Class","Month","Amount","Date"],...collections.map(x=>[x.receiptNo,x.studentName,x.roll,x.class,x.month,x.amount,x.date])],"dingel-hafizia-fee-records.csv")}
document.addEventListener("DOMContentLoaded",()=>{set("todayText",new Date().toLocaleDateString("bn-IN",{day:"numeric",month:"long",year:"numeric"}));$("loginForm").addEventListener("submit",handleLogin);$("addStudentForm").addEventListener("submit",saveStudent);$("collectionForm").addEventListener("submit",saveCollection);$("studentSearch").addEventListener("input",searchStudents);$("collectionSearch").addEventListener("input",searchCollections);$("collectionMonth").innerHTML=MONTHS.map(x=>`<option>${x}</option>`).join("");$("collectionDate").value=todayISO();$("collectionMonth").value=monthNow();$("collectionStudent").addEventListener("change",()=>{let s=students.find(x=>x.id===val("collectionStudent"));if(s&&!["Orphan","Poor"].includes(typeOf(s.type)))put("collectionAmount",s.monthly||"")});if(localStorage.getItem("dingelLoggedIn")==="true"){$("loginScreen").classList.add("hidden");$("app").classList.remove("hidden");loadApplicationData()}})
